version: "3"
services:
  nginx:
    image: pomerium/nginx-proxy:latest
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  distributedcache:
    environment:
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - NODES=distributedcache
    image: distributedcache
    expose:
      - 80
